In [1]:
import os
import pathlib
import pandas as pd

In [2]:
cols_prop = [
    "Asteroid_id",
    "H",
    "a_p",
    "e_p",
    "sin_i_p",
    "n",
    "g",
    "s",
    "LCE",
    "My"
]

In [3]:
core_path = os.getcwd()
prop_df = pd.read_csv("data/lvl1/proper_elements.syn", delimiter='\s+', skiprows=2, names=cols_prop)

/tmp/ipykernel_4381/454465210.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  prop_df = pd.read_csv("data/lvl1/proper_elements.syn", delimiter='\s+', skiprows=2, names=cols_prop)

In [4]:
prop_df.head()

,Asteroid_id,H,a_p,e_p,sin_i_p,n,g,s,LCE,My
0,1,3.41,2.767096,0.116198,0.167585,78.193318,54.070272,-59.170034,1.16,-2
1,2,4.17,2.770918,0.281258,0.547547,78.041654,-1.335344,-46.393342,44.20,10
2,3,5.36,2.669366,0.233506,0.229226,82.528181,43.635655,-61.222138,13.74,-2
3,4,3.31,2.361513,0.098758,0.111336,99.188833,36.872897,-39.597863,2.83,2
4,6,5.76,2.425271,0.158486,0.247863,95.303184,31.568209,-41.829042,4.56,2

In [5]:
cols_fam = [
    "Asteroid_id",
    "H",
    "status",
    "family_1",
    "dv_fam_1",
    "near_1",
    "family_2",
    "dv_fam_2",
    "near_2",
    "rescod"
]

In [6]:
family_df = pd.read_csv("data/lvl1/family_classification.famrec", delimiter='\s+', names=cols_fam, comment='%')

/tmp/ipykernel_4381/2552771411.py:1: DtypeWarning: Columns (0,5) have mixed types. Specify dtype option on import or set low_memory=False.
  family_df = pd.read_csv("data/lvl1/family_classification.famrec", delimiter='\s+', names=cols_fam, comment='%')

In [7]:
family_df.head()

,Asteroid_id,H,status,family_1,dv_fam_1,near_1,family_2,dv_fam_2,near_2,rescod
0,1,3.41,0,0,0.0,0,0,0.0,0,0
1,2,4.17,3,2,0.0,0,0,0.0,0,0
2,3,5.36,3,3,0.0,0,0,0.0,0,0
3,4,3.31,3,4,0.0,0,0,0.0,0,0
4,5,6.93,3,5,0.0,0,0,0.0,0,0

In [8]:
cols_rms = [
    "Asteroid_id",
    "a_p",
    "e_p",
    "sin_i_p",
    "n",
    "g",
    "s",
    "lam_fit_deg",
    "My"
]

In [9]:
RMS_mb_df = pd.read_csv("data/lvl1/RMS_main_belt.sig", delimiter='\s+', names=cols_rms, comment='%')

/tmp/ipykernel_4381/1710120328.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  RMS_mb_df = pd.read_csv("data/lvl1/RMS_main_belt.sig", delimiter='\s+', names=cols_rms, comment='%')

In [12]:
RMS_mb_df['a_p'] = RMS_mb_df['a_p'].map(lambda x: f"{x:.8f}")
RMS_mb_df['e_p'] = RMS_mb_df['e_p'].map(lambda x: f"{x:.7f}")
RMS_mb_df['sin_i_p'] = RMS_mb_df['sin_i_p'].map(lambda x: f"{x:.7f}")

In [13]:
RMS_mb_df.head()

,Asteroid_id,a_p,e_p,sin_i_p,n,g,s,lam_fit_deg,My
0,1,0.00000471,0.0014821,0.0000293,0.000169,0.005767,0.055891,97.2642,-2
1,2,0.00005325,0.0037414,0.0007473,0.003584,0.017078,0.018003,3385.2442,10
2,3,0.00000401,0.0000750,0.0000305,0.000123,0.003290,0.005535,57.0721,-2
3,4,0.00000002,0.0001210,0.0000717,0.000001,0.003256,0.003553,1.9958,2
4,6,0.00000097,0.0020045,0.0002046,0.000043,0.010758,0.032849,28.8165,2

In [15]:
pathlib.Path(os.path.join(core_path, "data/lvl2")).mkdir(parents=True, exist_ok=True)

prop_df.to_pickle(os.path.join(core_path, "data/lvl2", "prop_df.pkl"), protocol=4)
family_df.to_pickle(os.path.join(core_path, "data/lvl2", "family_df.pkl"), protocol=4)
RMS_mb_df.to_pickle(os.path.join(core_path, "data/lvl2", "RMS_mb_df.pkl"), protocol=4)